# Generated by Django 5.0 on 2024-01-01 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(verbose_name='max_length=250')),
                ('text', models.TextField()),
                ('publ', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Посты', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publ'],
                'indexes': [models.Index(fields=['-publ'], name='blog_post_publ_d2a3c8_idx')],
            },
        ),
    ]
